/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nitcmess;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Prashant
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        MessButton.setVisible(false);
        StudentButton.setVisible(false);
        CWardenButton.setVisible(false);
        log_manager.setVisible(false);
        log_warden.setVisible(false);
        log_student.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        CWardenButton = new javax.swing.JButton();
        StudentButton = new javax.swing.JButton();
        MessButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        log_student = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_p_stud = new javax.swing.JPasswordField();
        txt_uname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        FPASS_Student = new javax.swing.JButton();
        log_warden = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_p_cw = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        Warden_Log_Btn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Txt_W_Uname = new javax.swing.JTextField();
        FPASS_Warden = new javax.swing.JButton();
        log_manager = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_p_mess = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        Log_Btn_Manager = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txt_id_mess = new javax.swing.JTextField();
        FPass_Manager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSTEL MESS MANAGEMENT SYSTEM");

        LoginBtn.setBackground(new java.awt.Color(0, 0, 204));
        LoginBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("LOGIN");
        LoginBtn.setBorderPainted(false);
        LoginBtn.setContentAreaFilled(false);
        LoginBtn.setFocusPainted(false);
        LoginBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LoginBtnMouseMoved(evt);
            }
        });
        LoginBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginBtnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginBtnFocusLost(evt);
            }
        });
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
        });
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SIGN UP");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ABOUT");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LoginBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setEnabled(false);
        jPanel4.setFocusable(false);
        jPanel4.setOpaque(false);

        CWardenButton.setBackground(new java.awt.Color(255, 255, 255));
        CWardenButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alokk\\Downloads\\cutmypic (12).png")); // NOI18N
        CWardenButton.setBorderPainted(false);
        CWardenButton.setContentAreaFilled(false);
        CWardenButton.setFocusPainted(false);
        CWardenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CWardenButtonActionPerformed(evt);
            }
        });

        StudentButton.setBackground(new java.awt.Color(255, 255, 255));
        StudentButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alokk\\Downloads\\cutmypic (13).png")); // NOI18N
        StudentButton.setBorderPainted(false);
        StudentButton.setContentAreaFilled(false);
        StudentButton.setFocusPainted(false);
        StudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonActionPerformed(evt);
            }
        });

        MessButton.setBackground(new java.awt.Color(255, 255, 255));
        MessButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alokk\\Downloads\\cutmypic (14).png")); // NOI18N
        MessButton.setBorderPainted(false);
        MessButton.setContentAreaFilled(false);
        MessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CWardenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CWardenButton)
                    .addComponent(StudentButton)
                    .addComponent(MessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        log_student.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN STUDENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FPASS_Student.setForeground(new java.awt.Color(0, 102, 0));
        FPASS_Student.setText("Forgot Password");
        FPASS_Student.setBorderPainted(false);
        FPASS_Student.setContentAreaFilled(false);
        FPASS_Student.setFocusPainted(false);
        FPASS_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPASS_StudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout log_studentLayout = new javax.swing.GroupLayout(log_student);
        log_student.setLayout(log_studentLayout);
        log_studentLayout.setHorizontalGroup(
            log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(log_studentLayout.createSequentialGroup()
                .addGroup(log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(log_studentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(log_studentLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(log_studentLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_p_stud)))))
                    .addGroup(log_studentLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(FPASS_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        log_studentLayout.setVerticalGroup(
            log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_studentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(log_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_p_stud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(FPASS_Student)
                .addContainerGap())
        );

        log_warden.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN CHIEF WARDEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Password");

        Warden_Log_Btn.setBackground(new java.awt.Color(0, 102, 102));
        Warden_Log_Btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Warden_Log_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Warden_Log_Btn.setText("Login");
        Warden_Log_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Warden_Log_BtnActionPerformed(evt);
            }
        });

        Txt_W_Uname.setEditable(false);
        Txt_W_Uname.setText("Chief Warden");

        FPASS_Warden.setForeground(new java.awt.Color(0, 153, 51));
        FPASS_Warden.setText("Forgot Password");
        FPASS_Warden.setBorderPainted(false);
        FPASS_Warden.setContentAreaFilled(false);
        FPASS_Warden.setFocusPainted(false);
        FPASS_Warden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPASS_WardenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout log_wardenLayout = new javax.swing.GroupLayout(log_warden);
        log_warden.setLayout(log_wardenLayout);
        log_wardenLayout.setHorizontalGroup(
            log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(log_wardenLayout.createSequentialGroup()
                .addGroup(log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(log_wardenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(log_wardenLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_W_Uname, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                            .addGroup(log_wardenLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Warden_Log_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txt_p_cw)))))
                    .addGroup(log_wardenLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(FPASS_Warden, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        log_wardenLayout.setVerticalGroup(
            log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_wardenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_W_Uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(log_wardenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_p_cw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Warden_Log_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(FPASS_Warden)
                .addContainerGap())
        );

        log_manager.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN MESS MANAGER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mess Id");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Password");

        Log_Btn_Manager.setBackground(new java.awt.Color(0, 102, 102));
        Log_Btn_Manager.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Log_Btn_Manager.setForeground(new java.awt.Color(255, 255, 255));
        Log_Btn_Manager.setText("Login");
        Log_Btn_Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_Btn_ManagerActionPerformed(evt);
            }
        });

        FPass_Manager.setForeground(new java.awt.Color(0, 102, 0));
        FPass_Manager.setText("Forgot Password");
        FPass_Manager.setBorderPainted(false);
        FPass_Manager.setContentAreaFilled(false);
        FPass_Manager.setFocusPainted(false);
        FPass_Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPass_ManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout log_managerLayout = new javax.swing.GroupLayout(log_manager);
        log_manager.setLayout(log_managerLayout);
        log_managerLayout.setHorizontalGroup(
            log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(log_managerLayout.createSequentialGroup()
                .addGroup(log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(log_managerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, log_managerLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(log_managerLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(14, 14, 14)))
                        .addGroup(log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_id_mess, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Log_Btn_Manager, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txt_p_mess))))
                    .addGroup(log_managerLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(FPass_Manager, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        log_managerLayout.setVerticalGroup(
            log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_managerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_id_mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(log_managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_p_mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_Btn_Manager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(FPass_Manager)
                .addContainerGap())
        );

        jLayeredPane1.setLayer(log_student, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(log_warden, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(log_manager, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(log_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log_warden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(log_manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1258, 1258, 1258))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(log_manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(log_warden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(log_student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseMoved
        // TODO add your handling code here:


    }//GEN-LAST:event_LoginBtnMouseMoved

    private void LoginBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginBtnFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginBtnFocusGained

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        MessButton.setVisible(true);
        StudentButton.setVisible(true);
        CWardenButton.setVisible(true);
        log_warden.setVisible(false);
        log_student.setVisible(false);
        log_manager.setVisible(false);
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginBtnMouseExited

    private void LoginBtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginBtnFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginBtnFocusLost

    private void CWardenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CWardenButtonActionPerformed
        // TODO add your handling code here:
        StudentButton.setVisible(false);
        MessButton.setVisible(false);
        CWardenButton.setVisible(false);
        log_warden.setVisible(true);
    }//GEN-LAST:event_CWardenButtonActionPerformed

    private void StudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonActionPerformed
        // TODO add your handling code here:
        CWardenButton.setVisible(false);
        MessButton.setVisible(false);
        StudentButton.setVisible(false);
        log_student.setVisible(true);
    }//GEN-LAST:event_StudentButtonActionPerformed

    private void MessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessButtonActionPerformed
        // TODO add your handling code here:
        CWardenButton.setVisible(false);
        StudentButton.setVisible(false);
        MessButton.setVisible(false);
        log_manager.setVisible(true);

    }//GEN-LAST:event_MessButtonActionPerformed

    private void Warden_Log_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Warden_Log_BtnActionPerformed
        // TODO add your handling code here:
        String password=txt_p_cw.getText().toString();
        User US=new User();
        try {
            if(US.login(password))
            {
                this.setVisible(false);
                CWaeden CW=new CWaeden();
                CW.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Authentication Fail");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_Warden_Log_BtnActionPerformed

    private void FPASS_WardenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPASS_WardenActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        String who="Admin";
        ForgotPassword FP=new ForgotPassword(who);
        FP.setVisible(true);
    }//GEN-LAST:event_FPASS_WardenActionPerformed

    private void Log_Btn_ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_Btn_ManagerActionPerformed
        // TODO add your handling code here:
        String user=txt_id_mess.getText().toString();
        String pass=txt_p_mess.getText().toString();
        if(user.equals("")||pass.equals(""))
        {
         JOptionPane.showMessageDialog(null,"Fill All Details First");
        }
        else
        {
            CheckUser CU=new CheckUser();
            try {
                if(CU.checkMess(user))
                {
                    User U=new User();
                    if(U.login(user, pass,"Manager"))
                    {
                       this.setVisible(false);
                         MessMan MM=new MessMan(user);
                         MM.setVisible(true);
                    }
                    else
                    {
                     JOptionPane.showMessageDialog(null,"Authentication Fails");
                     txt_id_mess.setText("");
                     txt_p_mess.setText("");

                    }
                }
                else
                {
                   JOptionPane.showMessageDialog(null,"Invalid Mess Id");
                   txt_id_mess.setText("");
                   txt_p_mess.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }

        }
    }//GEN-LAST:event_Log_Btn_ManagerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String uname=txt_uname.getText().toString();
        String pass=txt_p_stud.getText().toString();
        User US=new User();
        try {
            if(US.login(uname, pass,"Student"))
            {
                this.setVisible(false);
                StudentProfile SP=new StudentProfile(uname);
                SP.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Authentication Fail");
                txt_uname.setText("");
                txt_p_stud.setText("");
            }
        } catch (SQLException ex) {
            System.err.println(ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentRegistration SR=new StudentRegistration();
        SR.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        About AB=new About();
        AB.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FPASS_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPASS_StudentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        String who="Student";
        ForgotPassword FP=new ForgotPassword(who);
        FP.setVisible(true);

    }//GEN-LAST:event_FPASS_StudentActionPerformed

    private void FPass_ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPass_ManagerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        String who="Manager";
        ForgotPassword FP=new ForgotPassword(who);
        FP.setVisible(true);
    }//GEN-LAST:event_FPass_ManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CWardenButton;
    private javax.swing.JButton FPASS_Student;
    private javax.swing.JButton FPASS_Warden;
    private javax.swing.JButton FPass_Manager;
    private javax.swing.JButton Log_Btn_Manager;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton MessButton;
    private javax.swing.JButton StudentButton;
    private javax.swing.JTextField Txt_W_Uname;
    private javax.swing.JButton Warden_Log_Btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel log_manager;
    private javax.swing.JPanel log_student;
    private javax.swing.JPanel log_warden;
    private javax.swing.JTextField txt_id_mess;
    private javax.swing.JPasswordField txt_p_cw;
    private javax.swing.JPasswordField txt_p_mess;
    private javax.swing.JPasswordField txt_p_stud;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
